### ISSUE TITLE
UserWarning: you defined a validation_step but have no val_dataloader. Skipping val loop

### ISSUE THREAD

**Issue by 7starsea** [PyTorchLightning/pytorch-lightning#10285]
## 🐛 Bug

Using pytorch-lightning 1.5.0rc1, I will get UserWarning:
```
pytorch_lightning/trainer/configuration_validator.py:156: UserWarning: you defined a validation_step but have no val_dataloader. Skipping val loop
  rank_zero_warn(f"you defined a {step_name} but have no {loader_name}. Skipping {stage} loop")
```
But with pytorch-lightning 1.4.9, there is no such warning.

### To Reproduce
```
import torch
from torch import nn
from collections import OrderedDict
import pytorch_lightning as pl

from torch.utils.data import DataLoader, TensorDataset


class TestLrModule(pl.LightningModule):
    def __init__(self, input_size, hidden_size):
        super(TestLrModule, self).__init__()
        self._fc = OrderedDict([
            ('fc0', nn.Linear(input_size, hidden_size)),
            ('tan0', nn.ReLU()),
            ('fc1', nn.Linear(hidden_size, 1)),
        ])
        self.fc = nn.Sequential(self._fc)
        self._loss_fn = nn.MSELoss()

    def forward(self, x):
        y = self.fc(x)
        return y.squeeze(dim=1)

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.forward(x)
        return self._loss_fn(y_hat, y)

    def training_epoch_end(self, outputs):
        loss = torch.mean(torch.stack([x['loss'] for x in outputs]))
        self.log('train_loss', loss, on_epoch=True)

    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.forward(x)
        return self._loss_fn(y_hat, y)

    def validation_epoch_end(self, outputs):
        loss = torch.mean(torch.stack(outputs))
        self.log('val_loss', loss, on_epoch=True)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=2e-3, weight_decay=1e-4)


sample, feature = 4000, 10
rx, ry = torch.rand(sample, feature), torch.rand(sample)
test_sample = int(sample * 0.2)
test_rx, test_ry = torch.rand(test_sample, feature), torch.rand(test_sample)

train_data = DataLoader(TensorDataset(rx, ry), batch_size=32, num_workers=2)
valid_data = DataLoader(TensorDataset(test_rx, test_ry), batch_size=32, num_workers=2)

m = TestLrModule(rx.shape[1], 16)
trainer = pl.Trainer(max_epochs=20)
trainer.fit(m, train_data, valid_data)
```

### Environment

- PyTorch Version  1.8.0
- Python version: 3.8.5
- OS (e.g., Linux): linux

**Comment by rohitgr7** [comment]
it was fixed recently. Can you try master?

**Comment by 7starsea** [comment]
Thanks. I will give it a shot.

**Comment by rohitgr7** [comment]
@7starsea apologies for the late reply. While accumulating, optimization doesn't happen at every step thus optimizer_step won't be called right after every training batch but only when the accumulation interval is complete. This is just a warning for the user to make sure they write their own custom logic within the `optimizer_step` taking the accumulation flag, set inside Trainer, into consideration.

**Comment by gezabohus** [comment]
This is still happening, pytorch-lightning 2.3.3, python 3.10.

**Comment by llctrautmann** [comment]
I am having the same issue with pytorch-lightning 2.3.3, python 3.11. Happy to share my training loop if that helps.
