### ISSUE TITLE
RAM not correctly released when training a pl module multiple times

### ISSUE THREAD

**Issue by CharlieCheckpt** [PyTorchLightning/pytorch-lightning#2010]
## 🐛 Bug

When I use the `pl.Trainer` multiple times (for instance when doing cross-validation), it seems that the ram is not completely released, as the ram memory usage increases over runs, in a strange way. 

![image](https://user-images.githubusercontent.com/10373261/83323799-60560900-a261-11ea-9620-153ca054975b.png)

### To Reproduce

1. Define a pl module and a pl.trainer inside a function, let's call it `train()`
2. call `train()` multiple times and track ram usage with `psutil` 

#### Code sample
```python
import psutil
from loguru import logger
import numpy as np
import torch
import pytorch_lightning as pl
from torch.utils.data import DataLoader, random_split
from torch.nn import functional as F
from torchvision.datasets import MNIST
from torchvision import transforms
import os


class LightningMNISTClassifier(pl.LightningModule):
    def __init__(self):
        super(LightningMNISTClassifier, self).__init__()

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, 128)
        self.layer_2 = torch.nn.Linear(128, 256)
        self.layer_3 = torch.nn.Linear(256, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        # (b, 1, 28, 28) -> (b, 1*28*28)
        x = x.view(batch_size, -1)
        # layer 1 (b, 1*28*28) -> (b, 128)
        x = self.layer_1(x)
        x = torch.relu(x)
        # layer 2 (b, 128) -> (b, 256)
        x = self.layer_2(x)
        x = torch.relu(x)
        # layer 3 (b, 256) -> (b, 10)
        x = self.layer_3(x)
        # probability distribution over labels
        x = torch.log_softmax(x, dim=1)
        return x

    def cross_entropy_loss(self, logits, labels):
        return F.nll_loss(logits, labels)

    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        logits = self.forward(x)
        loss = self.cross_entropy_loss(logits, y)

        logs = {'train_loss': loss}
        return {'loss': loss, 'log': logs}

    def prepare_data(self):
        # transforms for images
        transform = transforms.Compose([transforms.ToTensor(),
                                        transforms.Normalize((0.1307,), (0.3081,))])
        # prepare transforms standard to MNIST
        mnist_train = MNIST(os.getcwd(), train=True,
                            download=True, transform=transform)
        self.mnist_train, _ = random_split(mnist_train, [10_000, 50_000])

    def train_dataloader(self):
        return DataLoader(self.mnist_train, batch_size=1000, num_workers=3)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer


def train():
    model = LightningMNISTClassifier()
    trainer = pl.Trainer(
        checkpoint_callback=False,
        max_epochs=1
    )
    trainer.fit(model)


# train
rams_used = []
process = psutil.Process()
for _ in range(100):
    train()
    ram_used = process.memory_info()[0]/2.**30
    logger.warning(f"RAM USED : {ram_used}")
    rams_used.append(ram_used)

np.save("rams_used.npy", rams_used)

```

### Expected behavior

I would expect to observe the almost exact same ram usage after the training of the model. Indeed I compared it with native pytorch and did not observe any ram usage increase over runs.

### Environment
```
* CUDA:
        - GPU:
                - TITAN X (Pascal)
                - TITAN X (Pascal)
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.18.4
        - pyTorch_debug:     False
        - pyTorch_version:   1.5.0+cu101
        - pytorch-lightning: 0.7.6
        - tensorboard:       2.2.1
        - tqdm:              4.46.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.7.4
        - version:           #192-Ubuntu SMP Fri Sep 13 12:02:50 UTC 2019
```

### Additional context

I tried with older versions of lightning, and observed the same behaviour even in 0.7.1. 

The example above is with a small dataset of Mnist, but I encountered more impressive increase with a bigger dataset, as it ram went from 20Go to 65Go after 20 runs.

**Comment by williamFalcon** [comment]
could you put this on colab and show the ram graph there?

**Comment by CharlieCheckpt** [comment]
Thank you @williamFalcon , you can find below the graph, with the same code ran on [colab](https://colab.research.google.com/drive/1DABKcoxp9NukpVRWO50lG61yHul6Xm_a). 

![image](https://user-images.githubusercontent.com/10373261/83327743-6d352580-a27e-11ea-988a-00b7d75d0601.png)

**Comment by Borda** [comment]
any ideas what is happening here? shall be fixed in #2080

**Comment by karolpiczak** [comment]
I'm having similar issues with continual learning and calling fit multiple times. I've just rerun the provided colab notebook on Lightning 1.2.1 and it seems to persist:
![image](https://user-images.githubusercontent.com/215618/110100559-d49a7b80-7da2-11eb-9981-e03c15417974.png)

Any thoughts what could be causing this?

**Comment by Borda** [comment]
I look to me rather as a Python issue as the func does not return anything and shall be completely cleaned
```python
import gc
import time

def train():
    model = LightningMNISTClassifier()
    trainer = pl.Trainer(
        checkpoint_callback=False,
        max_epochs=1
    )
    trainer.fit(model)
    gc.collect()
    time.sleep(1)
```
I used the latest v1.2.10 and added garbage collector and 1s sleep at the end of the train func
![image](https://user-images.githubusercontent.com/6035284/116119855-2b477600-a6bf-11eb-847f-5f58a905a317.png)

**Comment by Abhishek-Prajapat** [comment]
It's 13-July-2021 and I assure you the issue still remains. I can run all 5 folds of training in native PyTorch but lightning gives OOM at the second epoch of the first fold.

**Comment by mddunlap924** [comment]
This issue still exists. Do you have any solutions that I can run to release the RAM?

**Comment by Abhishek-Prajapat** [comment]
@mddunlap924 I didn't found any precise solution so I just changed my code to accommodate it. I really want PyTorch to bring some sort of garbage collection for their Trainer.

**Comment by Ajk4** [comment]
+1, if I do regular pytorch loop its fine. With pytorch lightning I get OOMs

**Comment by mddunlap924** [comment]
Has there been any updates on this issue? Could anyone share a workaround they are using to handle this issue? The OOM is still occurring and prevents me from training multiple folds of data sequentially. The code provided at the top of this forum describes the issue very well.

**Comment by towr** [comment]
Adding `gc.collect()` in the loop eliminated the issue for me (as suggested above by Borda).

Also keep in mind that python takes a while to do garbage collection by itself. And even when it does, it may not release all memory back to the system (it may keep some to reuse).

If after adding `gc.collect()` someone still has issues with OOM, maybe you can investigate what objects are building up over time with:
    import gc
    from collections import Counter

    def get_current_object_names():
        gc.collect()
        objects = gc.get_objects()
        names = []
        for o in objects:
            try:
                names.append(f'{o.__class__.__module__}.{o.__class__.__name__}')
            except ReferenceError:
                pass
            
        return Counter(names)
        
(You can subtract one counter from the other to see how many extra objects have been added each iteration.)
