### ISSUE TITLE
pl+wandb: Hanging during "cleaning up ddp environment" when using DDPSpawnPlugin + WandbLogger

### ISSUE THREAD

**Issue by EricCousineau-TRI** [PyTorchLightning/pytorch-lightning#6106]
## 🐛 Bug

When using an accelerator that bascially uses a "spawn" start method for `multiprocessing` (rather than Linux default "fork"), any program that actually spawns a new worker (`num_processes>1`) seems to hang upon cleanup.

Concretely, I've only seen this when:
- Accelerator is either `ddp_cpu` or `ddp_spawn`; AND
- WandbLogger is instantiated (and I guess used for training)

## Please reproduce using the BoringModel

My model (`ConstantMultiply`) is more boring ;)

### To Reproduce

Clone this repo (it's small), and then run the example:
https://github.com/EricCousineau-TRI/repro/tree/cae9aa31f07f90c4cfb3b908fe84107e102ab06f/python/wandb_pytorch_lightning_combo
```
git clone https://github.com/EricCousineau-TRI/repro
cd repro
git checkout cae9aa31f07f90c4cfb3b908fe84107e102ab06f
cd python/wandb_pytorch_lightning_combo
./isolate.sh ./setup.sh ./train_wandb_pl_main.py
```

Ignore the stuff about sweeps for now (I can make less noisy dir if you want).

### Expected behavior

It doesn't freeze?

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux, Ubuntu, 18.04
 - How you installed PyTorch: pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.9, 3.8.0
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: :cry: 

### Additional context

It would be nice to have a "fork" version of DDP for CPU, so that way we can test things more easily for the suggested mode of DDP for GPU (per the PL docs, at least as of a couple of days ago).

If I use `ddp`, that means that colleagues who have only 1 GPU cannot test it, which hurts development, b/c the intended abstractions of `pl` breakdown :crying_cat_face: 
(When trying with `num_processes=2, gpus=[0]`, it just reduces the number of workers, so then we don't test those branches...)

The interactions between `wandb` and `pl` are a bit non-trivial, esp. if we want to try things like sweeps. We can hack around it, but jeepers it feels like flailing when doing it on the full setup.

**Comment by EricCousineau-TRI** [comment]
Referenced code that I used to check that DDP for CPU uses spawn:
https://github.com/PyTorchLightning/pytorch-lightning/blob/1.2.0/pytorch_lightning/trainer/connectors/accelerator_connector.py#L360-L392

**Comment by EricCousineau-TRI** [comment]
Also, I dunno if this is a `pl` problem, or a `wandb` problem, but I think since it's namely when pl re-spawns, it may be a PL issue?
(unless there's a min-repro that shows wandb being the culprit?)

**Comment by EricCousineau-TRI** [comment]
Briefly tried using `DDPPlugin` with CPU devices, but it hung at start-up (gave up w/in 15min):
https://github.com/EricCousineau-TRI/repro/commit/14b28f5750267d74fa96afd2e10f75aff798fba8

Also briefly tried doing a `DDPForkPlugin` for use with CPU, but also got confused (given baked-in logic about re-santizing GPUs in child procs); gave up w/in 15min:
https://github.com/EricCousineau-TRI/repro/commit/0c39778309067165b972bbfa90bc3610557b861d

**Comment by tyomhak** [comment]
hey @EricCousineau-TRI , which wandb versions are you experiencing these issues with?

**Comment by tyomhak** [comment]
Also, if this worked previously, can you check which wandb version was used at the time?

**Comment by EricCousineau-TRI** [comment]
Howdy Artyom! Experiencing this with `wandb==0.10.19`.

I thought it worked previously, but am unable to reproduce any of it within `pip` package versions, docker containers, diff machine, etc, so dunno if something else changed, or if I was observing the wrong thing.
FWIW Tried out `wandb` `0.9.4` and `0.10.2`; those fail too, though with some slightly diff. results: [commit](https://github.com/EricCousineau-TRI/repro/commit/1f372b088c286bd4cc2a8323353f28e815a43ca2)

**Comment by borisdayma** [comment]
I've not been able to reproduce your example yet but you could try to set the following environment variable:
`WANDB_START_METHOD=fork`

**Comment by EricCousineau-TRI** [comment]
Just added that here: [commit](https://github.com/EricCousineau-TRI/repro/commit/bedbcb3d) (also upgraded to wandb==0.10.20)
Still freezes :(

> I've not been able to reproduce your example yet [...]

Can I ask which part isn't reproducible? Does the repro command not execute (e.g. my bash scripting is bad), or does it run on you machine without a problem?

**Comment by borisdayma** [comment]
Howdy Eric!

Thanks for documenting so well these tests within your code.

I confirm the bug and made a simple colab to quickly explore it: [colab link](https://colab.research.google.com/drive/1aiaLFGde93OpW4F0cWJcTwuj_Mnk2e46?usp=sharing)

**Comment by borisdayma** [comment]
Just a note that we are still actively working on it

**Comment by borisdayma** [comment]
Still open and being worked on

**Comment by EricCousineau-TRI** [comment]
Is this still being worked on?

**Comment by bellhyeon** [comment]
same issue here

**Comment by thiyagu-lily** [comment]
Hi @borisdayma 
Is there a work around to prevent this issue?

**Comment by borisdayma** [comment]
Yes, a new experimental handling of multiprocessing environments is coming up and is being tested. Hopefully it will be ready this month.

**Comment by EricCousineau-TRI** [comment]
Any updates on this front? (and can this issue be reopened until it's actually resolved?)

I confirmed this is still an issue in our codebase for pytorch 1.10.2 + pytorch-lightning 1.5.8 + wandb 0.12.7.

I also saw the recommendations for freezing before / after training:
https://docs.wandb.ai/guides/track/advanced/distributed-training
However, `WANDB_START_METHOD=thread` and/or `wand.finish()` at the end do not seem to fix this - either it still hangs, or it complains about an `EOFError`.

**Comment by JohnKilbride** [comment]
I am experiencing a similar issue.

**Comment by borisdayma** [comment]
This should now be solved with latest lightning master branch.

```
pip install --upgrade wandb
pip install --upgrade git+https://github.com/PytorchLightning/pytorch-lightning.git
```

**Comment by EricCousineau-TRI** [comment]
Confirmed - thanks!!!
https://github.com/EricCousineau-TRI/repro/commit/9aef82f1

**Comment by yuvalkirstain** [comment]
@borisdayma When I try to install `git+https://github.com/PytorchLightning/pytorch-lightning.git` it fails because we do not have `git-lfs` installed (I do not have sudo permissions). What can I do to use the fix?
Thank you!

**Comment by EricCousineau-TRI** [comment]
I encountered same, but it was b/c my system was not properly configured. My `~/.gitconfig` had `lfs` section (carryover from prior install), but I did not have `git-lfs` installed.

My solution was to remove the offending section in the config. You may want to consider commenting out or `git lfs uninstall`, but consider backing up your config. (I version control mine.)
Be sure to read docs.

**Comment by mmiakashs** [comment]
I am still facing the same issue. Trainer just stuck after completing all the training and validation epochs. It just does not exit from the trainer fit loop. I am using ddp_spawn with 4 GPUs in a cluster slurm environment. I am using 
pytorch 1.11 and pytorch lightning 1.6.1 and wandb 0.12.4
Is there any fix for that?

**Comment by kptkin** [comment]
Hi @mmiakashs, 
Could you try upgrading to the latest version of `wandb` and let us know if this solves your issue? 
I think it should be resolved in the latest version.
