### ISSUE TITLE
Pickle error and OOM when upgrading to 1.2.0

### ISSUE THREAD

**Issue by phihung** [PyTorchLightning/pytorch-lightning#6173]
When upgrading from 1.1.6 to 1.2.0, I notices 2 changes
- Significant increase of gpu memory 
- Pickle error in my module class (the object `metric_fn` is sure not pickable but the same code worked fine in 1.1.6)

Do you have an idea what changes in 1.2.0 may cause the issues ?
Any suggestion for the memory problem ?

My pseudo code
```python
class ClfModule(pl.LightningModule):
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        self.metric_fn = not_pickable_object()
```
I am using Huggingface transformers and datasets

**Comment by angadkalra** [comment]
I noticed GPU memory increase too. My original data image size didn't work when going from 1.1.8 to 1.2.

**Comment by SkafteNicki** [comment]
Gpu memory problem should be fixed in v1.2.1.
What accelator are you using? `ddp_spawn` requires that everything can be pickled.

**Comment by angadkalra** [comment]
@phihung My OOM went away with upgrade to v1.2.1 and using DDP. Please try.

**Comment by tchaton** [comment]
Dear @angadkalra,

Were using using AMP ? In 1.2.0, there were a hot bug and it wasn't applied properly. Which could explain our OOM.

Best,
T.C

**Comment by phihung** [comment]
Hi SkafteNicki, hi angadkalra,
Thanks for your help
I confirm that upgrading to 1.2.1 solves OOM problem.

The pickle problem remains. I've tried the following
```
pl.Trainer(precision=16)
pl.Trainer(precision=16, accelerator="ddp_spawn")
pl.Trainer(precision=16, accelerator="ddp")
pl.Trainer(precision=16, accelerator="ddp")
``` 
What was the default in 1.1.6 ?

**Comment by SkafteNicki** [comment]
@phihung can you post a model where I can reproduce your pickle error?
Also, what prevents you from transforming your non-pickle object into a pickable object?
