### ISSUE TITLE
apply_func.py: from torchtext.legacy.data import Batch

### ISSUE THREAD

**Issue by dbonner** [PyTorchLightning/pytorch-lightning#6210]
## 🐛 Bug

In the latest torchtext (version 0.9.0a0+036df73) built from source:
The name Batch is no longer located under torchtext.data
Batch is now located under torchtext.legacy.data

--Error message--
File "/home/daniel/py38/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 28, in <module>                                                      
    from torchtext.data import Batch                                                  
ImportError: cannot import name 'Batch' from 'torchtext.data' (/home/daniel/py38/lib/python3.8/site-packages/torchtext/data/__init__.py)

You can fix this by changing line line 28 of pytorch_lightning/utilities/apply_func.py to:
    from torchtext.legacy.data import Batch

This does not reproduce with BoringModel because BoringModel does not import torchtext.data.Batch

### Expected behavior
No error message.

### Environment
* CUDA:
        - GPU:
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
        - available:         True
        - version:           11.2
* Packages:
        - numpy:             1.19.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0a0+92a4ee1
        - pytorch-lightning: 1.1.5
        - torchtext: 0.9.0a0+036df73     <--------------------------
        - tqdm:              4.57.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.8
        - version:           #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021

**Comment by dbonner** [comment]
This should fix it:
https://github.com/PyTorchLightning/pytorch-lightning/pull/6211
I was able to successfully create the option to use torchtext.legacy.data or torchtext.data depending on the torchtext version after my 3rd commit on this pull request.

**Comment by dbonner** [comment]
My fourth commit in the pull request (#6211 ) uses distutils.version.LooseVersion

**Comment by dbonner** [comment]
Thanks everyone :)

**Comment by TheBoss313** [comment]
It still fails when Run on Google Colab, as seen in [Unable to import pytorch_lightning on google colab](https://stackoverflow.com/questions/66538407/unable-to-import-pytorch-lightning-on-google-colab) and yes it has been tested.

**Comment by monkiravn** [comment]
> It still fails when Run on Google Colab, as seen in [Unable to import pytorch_lightning on google colab](https://stackoverflow.com/questions/66538407/unable-to-import-pytorch-lightning-on-google-colab) and yes it has been tested.
I have the same problem as you. Have you fixed it?
I

**Comment by TheBoss313** [comment]
Kind of. If you look at the Stack page that I linked, you will see two solutions. Both work.   
One installs the pytorch_lightning straight from here(GitHub).  
The second does some string of installs and it works, but if you do the installs separately, it fails.  
```
!pip install torchtext==0.8.0 torch==1.7.1 pytorch-lightning==1.2.2
```
That works in this Colab notebook:  https://colab.research.google.com/drive/1GSCd3Gz3EOQIln3v065VKWKbB3_F8xqK?usp=sharing  
My solution installs the newest version of pytorch_lightning, including development versions.  
```
!pip install git+https://github.com/PyTorchLightning/pytorch-lightning
```

**Comment by Dheeraj-Arremsetty** [comment]
I have followed the above instructions, and when I have installed it. I can see this error message. Is this ok to ignore this message?

![image](https://user-images.githubusercontent.com/8819938/110788749-a69ab880-8234-11eb-9a07-b52a4b060aaf.png)

**Comment by TheBoss313** [comment]
You won't be able to use the torchvision package/module, if you use that solution. If you use the other one, and use the comment that has been added, you can use everything (I think).

**Comment by Stevenmch** [comment]
Thank you so much

**Comment by krishnaaxo** [comment]
Thank you.
